---
# Source: showks-canvas/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-canvas-kojiha
  namespace: showks
  labels:
    app: showks-canvas-kojiha
    class: showks-canvas
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app-port
  selector:
    app: showks-canvas-kojiha

---
# Source: showks-canvas/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-canvas-kojiha
  namespace: showks
  labels:
    app: showks-canvas-kojiha
    class: showks-canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-canvas-kojiha
  template:
    metadata:
      labels:
        app: showks-canvas-kojiha
        class: showks-canvas
    spec:
      containers:
        - name: showks-canvas-kojiha
          image: containerdaysjp/showks-canvas-kojiha:prod-9fa18231e4730b2dc8edc58f23b1aeb3e873abd0
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP

---
# Source: showks-canvas/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-canvas-kojiha
  namespace: showks
  labels:
    class: showks-canvas
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: showks-canvas-kojiha.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-canvas-kojiha
          servicePort: 8080
  - host: showks-canvas-kojiha.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-canvas-kojiha
          servicePort: 8080

