---
# Source: showks-canvas/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-canvas-kojiha
  namespace: showks
  labels:
    app: showks-canvas
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app-port
  selector:
    app: showks-canvas


---
# Source: showks-canvas/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-canvas-kojiha
  namespace: showks
  labels:
    app: showks-canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-canvas
  template:
    metadata:
      labels:
        app: showks-canvas
    spec:
      containers:
        - name: showks-canvas-kojiha
          image: containerdaysjp/showks-canvas-kojiha:prod-d186333a32e0312fef5a9476d4195f84385522e5
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP

