---
# Source: showks-canvas/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-canvas-jacopen
  namespace: showks
  labels:
    app: showks-canvas-jacopen
    class: showks-canvas
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: app-port
  selector:
    app: showks-canvas-jacopen

---
# Source: showks-canvas/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-canvas-jacopen
  namespace: showks
  labels:
    app: showks-canvas-jacopen
    class: showks-canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-canvas-jacopen
  template:
    metadata:
      labels:
        app: showks-canvas-jacopen
        class: showks-canvas
    spec:
      containers:
        - name: showks-canvas-jacopen
          image: gcr.io/ipc-containerdays/showks-canvas-jacopen:prod-8458a6516b5b2b6d6c00a4abfc1d86ab0782dad0
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP

---
# Source: showks-canvas/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-canvas-jacopen
  namespace: showks
  labels:
    class: showks-canvas
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: showks-canvas-jacopen.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-canvas-jacopen
          servicePort: 8080

