apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-portal-frontend
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  rules:
  - host: portal.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-portal-frontend-temp
          servicePort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-portal-frontend
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: portal.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-portal-frontend
          servicePort: 3000
